# Configuración del Agente Personalizado
app:
  name: "Agente Personalizado"
  version: "1.0.0"
  theme: "dark"
  
# Configuración de LLM
llm:
  provider: "lm_studio"  # opciones: "lm_studio", "openai"
  lm_studio:
    base_url: "http://localhost:1234/v1"
    model: "local-model"
  openai:
    api_key: ""  # Configurar tu API key aquí
    model: "gpt-3.5-turbo"

# Rutas de archivos
paths:
  documents_output: "./documents"
  presentations_output: "./presentations" 
  logs: "./logs"
  temp: "./temp"

# Configuración de la interfaz
ui:
  window:
    title: "Agente Personalizado - Control Panel"
    width: 1200
    height: 800
    min_width: 800
    min_height: 600
  
  colors:
    primary: "#2D3748"
    secondary: "#4A5568"
    accent: "#3182CE"
    background: "#1A202C"
    surface: "#2D3748"
    text_primary: "#F7FAFC"
    text_secondary: "#A0AEC0"
    success: "#38A169"
    warning: "#D69E2E"
    error: "#E53E3E"

# Scripts y herramientas disponibles
tools:
  document_generation:
    - name: "Generar Documento Word"
      description: "Crea un documento de Word con contenido personalizado"
      enabled: true
    - name: "Generar Presentación PowerPoint"
      description: "Crea una presentación de PowerPoint"
      enabled: true
  
  web_tools:
    - name: "Web Scraping"
      description: "Extrae información de sitios web"
      enabled: true
    - name: "Análisis de Datos Web"
      description: "Analiza y procesa datos extraídos de la web"
      enabled: true
  
  llm_tools:
    - name: "Consulta LLM"
      description: "Realiza consultas al modelo de lenguaje configurado"
      enabled: true
    - name: "Procesamiento de Texto"
      description: "Procesa y analiza texto usando IA"
      enabled: true

# Configuración de logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "[{time}] {level}: {message}"
  max_lines: 1000